---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    permissions:
      id-token: write
      contents: read

    steps:
      # ...
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "MetaParser.zip"
          token: ${{ secrets.GITHUB_TOKEN }}  
