name: Publish

on:
  push:
    tags:
      - '*'
    branches:
      - "master"

jobs:
  publish:
    permissions: write-all
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: Archive/MetaParser.zip
            asset_name: metaparser-windows-amd64.zip

    steps:
    - uses: actions/checkout@v3
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: Release

